spring.application.name=pedidos-integrado-legacy
spring.datasource.url=jdbc:h2:mem:pedidos-legacy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=localhost
spring.mail.port=1025
